path: C:/Users/ACER/Desktop/Helmet_Detection/data

train: C:/Users/ACER/Desktop/Helmet_Detection/data/train/images
val: C:/Users/ACER/Desktop/Helmet_Detection/data/val/images

nc: 17
names: ['dog','person','tv','car','cat','meatballs','marinara sauce','tomato soup','chicken noodle soup','french onion soup','chicken breast','ribs','pulled pork','hamburger','cavity','helmet','safety jacket']